# Generated by Django 5.1.5 on 2025-01-25 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='company/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('EC', 'ECOMMERCE'), ('SU', 'STARTUP'), ('HW', 'HARDWARE'), ('SW', 'SOFTWARE')], max_length=2)),
            ],
        ),
    ]
