# Generated by Django 5.1.5 on 2025-01-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvarity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
